# This workflow builds continuous documentation using Dokka and GitHub Pages.
# Source: https://github.com/kwebio/kweb-core/blob/master/.github/workflows/build.yml

name: dokka-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and run tests
        run: ./gradlew build
      - name: Generate API documentation
        if: ${{github.event_name == 'push'}}
        run: ./gradlew dokkaHtml
      - name: Deploy API documentation to Github Pages
        if: ${{github.event_name == 'push'}}
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          BRANCH: gh-pages
          FOLDER: docs